export const SIMPLE_ADD_ACTION = "SIMPLE_ADD_ACTION";
export const SIMPLE_REMOVE_ACTION = "SIMPLE_REMOVE_ACTION";
export const SIMPLE_VISIBLE = "SIMPLE_VISIBLE";
export const SIMPLE_RESET = "SIMPLE_RESET";
